### PR TITLE
Fixed wrong index being used.

### PR DESCRIPTION
**Pull request by aashish24**
@sankhesh @dlonie  please review.

### CODE REVIEW

**Comment by aashish24** [comment]
Ref: https://github.com/UV-CDAT/uvcdat/pull/1560

**Comment by doutriaux1** [comment]
@aashish24 which PR needs this? Should I wait before merging anything back into master?

**Comment by alliepiper** [comment]
LGTM

**Comment by aashish24** [comment]
@doutriaux1 it will be for #1560 as I linked earlier.

**Comment by aashish24** [comment]
Ref: UV-CDAT/uvcdat#1560

**Pull request merged**
