### PR TITLE
Actors in context

### PR DESCRIPTION
**Pull request by alliepiper**
Note that this isn't a proper merge request and cannot be merged, since we have a diverged fork of VTK and are using a rebase workflow. This branch would replace the current uvcdat-master, not merge into it. This branch contains the UVCDAT modifications on top of the current (as of 11/6) VTK master, which includes the new context 2D features.

The two main additions to the Context2D framework are:
- `Rendering/Context2D/*vtkPropItem*`: Allows any vtkProp subclass (e.g. vtkActor) to be used as a vtkContextItem in a vtkContextScene.
  https://github.com/UV-CDAT/VTK/blob/actors_in_context_uvcdat/Rendering/Context2D/vtkPropItem.h
- `Charts/Core/*vtkContextArea*`: Sets up a transformed and clipped area with labeled axes to which vtkContextItems may be added. 
  https://github.com/UV-CDAT/VTK/blob/actors_in_context_uvcdat/Charts/Core/vtkContextArea.h

There is a test which exercises and demonstrates this functionality here:

https://github.com/UV-CDAT/VTK/blob/actors_in_context_uvcdat/Charts/Core/Testing/Cxx/TestPropItem.cxx

That test renders the following image:

result

The new classes are documented in the linked header files, and the test should show how they are used. Let me know if there is any missing functionality or new subclasses of vtkContextItem that would be useful.

Let me know if there are any questions.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dlonie I'm on my mac today. Is it somewhat working on Mac? Do you want me to try anything for you?

**Comment by alliepiper** [comment]
It works in mac, it's just an issue with the labeled contour mapper. For some reason, embedding that mapper in the context2D environment is breaking the stenciling used to 'blank out' the lines behind the labels, and only on mac. I'm poking around on a mac here to see what's going on, hopefully it'll be something obvious :D

**Comment by doutriaux1** [comment]
That sounds like a similar issue as what breaks our RH6 builds, hopefully you'll find it quick.

**Comment by alliepiper** [comment]
The mac issue is fixed. It was not related to the RedHat stencil issue.

I've updated this PR with the fix.

**Comment by alliepiper** [comment]
Updated PR to use current VTK master, which includes the new context2D features. See note about applying it in the PR description.

**Pull request closed without merging**
