### PR TITLE
Uvcdat master bump 27052015 6d673347

### PR DESCRIPTION
**Pull request by alliepiper**

### CODE REVIEW

**Comment by alliepiper** [comment]
Goes with UV-CDAT/uvcdat#1348

**Comment by doutriaux1** [comment]
@dlonie ooops conflicts.... Please fix so I can merge again! Will revert the merge I just did I guess...

**Comment by alliepiper** [comment]
Derp, my bad.

Since the uvcdat-master branch diverges from upstream (there are some commits on top that we just rebase under), we can't updating via merge requests. We'll need to just push the branch directly instead. I'll go ahead and do this, since the rest of the projects are updated already :+1:

**Comment by alliepiper** [comment]
Actually, I'm not sure what happened -- I'll post in the main PR for this change, UV-CDAT/uvcdat#1348

**Comment by alliepiper** [comment]
Pushed manually.

**Pull request merged**
